import * as Yup from "yup";

export const EmployeeValidationSchema = Yup.object().shape({
  employee_id: Yup.number().required("Employee ID is required").min(1, "Employee Id must be 1 or more"),
  personal_number: Yup.string().matches(/^\d{1,10}$/,).required("Personal number is required").min(10,"Personal number should not be less than 10 characters").max(10,"Personal number should not exceed 10 characters"),
  first_name: Yup.string().required("First name is required"),
  last_name: Yup.string().required("Last name is required"),
  bank: Yup.string().required("Bank name is required"),
  bank_account_number: Yup.string().required("Bank account number is required"),
  IFSC: Yup.string().required("IFSC code is required"),
  date_of_joining: Yup.date().required("Date of joining is required"),
  location: Yup.string().required("Location is required"),
  department: Yup.string().required("Department is required"),
  designation: Yup.string().required("Designation is required"),
  email: Yup.string().email("Invalid email format"),
  project: Yup.string().required("Project name is required"),
  employee_type: Yup.string().required("Employee type is required"),
  gender: Yup.string().required("Gender is required"),
  date_of_birth: Yup.date().required("Date of birth is required"),
  panCard: Yup.string().required("Pancard number is required"),
  aadharCard: Yup.string().required("Aadhar card number is required"),
  manager_id: Yup.number().required("Manager Id is required").min(1, "Manager Id must be 1 or more"),
  supervisor_id: Yup.number().required("Supervisor Id is required").min(1, "Supervisor Id must be 1 or more"),
  country: Yup.string().required("Country is required"),
  state: Yup.string().required("State is required"),
  zipcode: Yup.string().required("Zipcode is required"),
  supervisor_name: Yup.string().required("Supervisor's name is required"),
  manager_name: Yup.string().required("Manager's name is required"),
  total_experience: Yup.number().min(0, "Total experience must be 0 or more"),
  marital_status: Yup.string().required("MArital status is required"),
  emergency_contact_name: Yup.string().required("Emergency contact name is required"),
  emergency_contact_number: Yup.string().required("Emergency contact number is required"),
  emergency_contact_relationship: Yup.string().required("Emergency contact's relationship is required"),
  address_line_1: Yup.string().required("Address line 1 is required"),
  address_line_2: Yup.string().required("Address line 2 is required"),
  city: Yup.string().required("City is required"),
  emergency_contact_email: Yup.string().email("Invalid email format"),
  passport_number: Yup.string().required("Passport number is required"),
  passport_expiry_date: Yup.date().required("Passport expiry date is required"),
  driving_license_number: Yup.string().required("Driving licence number is required"),
  driving_license_expiry_date: Yup.date().required("Driving licence expiry date is required"),
  educational_qualification: Yup.string().required("Educational qualification is required"),
  bank_branch: Yup.string().required("Bank branch is required"),
  bank_branch_address: Yup.string().required("Bank branch address is required"),
  password: Yup.string().required("Password is required")
});
