export interface FormData {
  id?: undefined|number;
  employee_id: undefined | number;
  total_working_days: undefined | number;
  present_working_days: undefined | number;
  period: string;
  basic_salary: undefined | number;
  house_rent_allowance: undefined | number;
  special_allowance: undefined | number;
  conveyance: undefined | number;
  additional_special_allowance: undefined | number;
  on_call_shift_allowance: undefined | number;
  stat_bonus: undefined | number;
  provident_fund: undefined | number;
  professional_tax: undefined | number;
  income_tax: undefined | number;
  gross_earning: undefined | number;
  gross_deduction: undefined | number;
  net_pay: undefined | number;
  overtime_hours: undefined | number;
  overtime_pay: undefined | number;
  bonus: undefined | number;
  commission: undefined | number;
  reimbursement: undefined | number;
  other_allowances: undefined | number;
  deduction_details: string;
  remarks: string;
  employee_rating: undefined | number;
  performance_bonus: undefined | number;
  shift_allowance: undefined | number;
  medical_allowance: undefined | number;
  leave_balance: undefined | number;
  loan_deduction: undefined | number;
  insurance_premium: undefined | number;
  attendance_bonus: undefined | number;
  travel_allowance: undefined | number;
  uniform_allowance: undefined | number;
  training_allowance: undefined | number;
  other_deductions: undefined | number;
  bonus_details: string;
  incentive: undefined | number;
  tax_deduction_at_source: undefined | number;
  salary_advance: undefined | number;
  loan_balance: undefined | number;
  payment_mode: string;
  payment_date: string;
}
export interface GeneratedPayslipResponse {
  data?: {
    createdUserData: {
      employee_id: number;
      total_working_days: number;
      present_working_days: number;
      period: string;
      basic_salary: number;
      house_rent_allowance: number;
      special_allowance: number;
      conveyance: number;
      additional_special_allowance: number;
      on_call_shift_allowance: number;
      stat_bonus: number;
      provident_fund: number;
      professional_tax: number;
      income_tax: number;
      gross_earning: number;
      gross_deduction: number;
      net_pay: number;
      overtime_hours: number;
      overtime_pay: number;
      bonus: number;
      commission: number;
      reimbursement: number;
      other_allowances: number;
      deduction_details: string;
      remarks: string;
      employee_rating: number;
      performance_bonus: number;
      shift_allowance: number;
      medical_allowance: number;
      leave_balance: number;
      loan_deduction: number;
      insurance_premium: number;
      attendance_bonus: number;
      travel_allowance: number;
      uniform_allowance: number;
      training_allowance: number;
      other_deductions: number;
      bonus_details: string;
      incentive: number;
      tax_deduction_at_source: number;
      salary_advance: number;
      loan_balance: number;
      payment_mode: string;
      payment_date: string;
    };
    message: string;
    Status: string;
    code: string;
  };
  error?: {
    message: string;
    status: string;
    code: number;
  };
}
