export const initialValues = {
  id:0,
    employee_id: 0 ,
    total_working_days: 0 ,
    present_working_days: 0 ,
    period: '',
    basic_salary: 0 ,
    house_rent_allowance: 0 ,
    special_allowance: 0 ,
    conveyance: 0 ,
    additional_special_allowance: 0 ,
    on_call_shift_allowance: 0 ,
    stat_bonus: 0 ,
    provident_fund: 0 ,
    professional_tax: 0 ,
    income_tax: 0 ,
    gross_earning: 0 ,
    gross_deduction: 0 ,
    net_pay: 0 ,
    overtime_hours: 0 ,
    overtime_pay: 0 ,
    bonus: 0 ,
    commission: 0 ,
    reimbursement: 0 ,
    other_allowances: 0 ,
    deduction_details: '',
    remarks: '',
    employee_rating: 0 ,
    performance_bonus: 0 ,
    shift_allowance: 0 ,
    medical_allowance: 0 ,
    leave_balance: 0 ,
    loan_deduction: 0 ,
    insurance_premium: 0 ,
    attendance_bonus: 0 ,
    travel_allowance: 0 ,
    uniform_allowance: 0 ,
    training_allowance: 0 ,
    other_deductions: 0 ,
    bonus_details: '',
    incentive: 0 ,
    tax_deduction_at_source: 0 ,
    salary_advance: 0 ,
    loan_balance: 0 ,
    payment_mode: '',
    payment_date: ''
  };

